FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

RUN apk add --no-cache nmap && \
    addgroup -S scanner && adduser -S scanner -G scanner
USER scanner

COPY eqima-scanner-1.0.0.jar app.jar

EXPOSE 8085

ENTRYPOINT ["java", \
  "-XX:+UseZGC", \
  "-XX:+ZGenerational", \
  "-Djava.security.egd=file:/dev/./urandom", \
  "-jar", "app.jar"]